# Generated by Django 4.1.1 on 2022-11-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message_delete_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receipient',
            new_name='recipient',
        ),
    ]
